// GET /api/dashboard/recipes?agent=<slug>
// GET /api/dashboard/recipes?category=<prefix>
// GET /api/dashboard/recipes              (grand view, all recipes)
//
// R41 -- recipes book backend. Reads the build-time src/data/skills.json
// (generated by scripts/build-skills-index.js from AOM-EA's .claude/skills/
// INDEX.md) and returns recipes in user-friendly shape: name, one-line
// description, category, categoryLabel.
//
// Filtering:
//   - ?agent=<slug>: returns recipes for that agent's domain. The agent->
//     category mapping lives in AGENT_CATEGORIES below and mirrors the
//     `.claude/rules/suggest-skills.md` cheat-sheet.
//   - ?category=<prefix>: return recipes whose category equals the prefix
//     (useful for the grand-view search of "video", "brand", etc.).
//   - No filter: returns every recipe (grand view).
//
// Response:
//   {
//     count: number,
//     recipes: [{ name, alias?, description, category, categoryLabel }],
//     categories: [{ category, label, count }]
//   }

import { readFileSync } from 'fs'
import { join } from 'path'

// Mirrors .claude/rules/suggest-skills.md "Agents and Their Skill Domains".
const AGENT_CATEGORIES = {
  bobby: ['web', 'corner'],
  colton: ['web', 'corner'],
  cleo: ['video', 'audio', 'resolve'],
  steffen: ['brand'],
  tony: ['social'],
  jacob: ['outreach'],
  alex: ['biz'],
  steve: ['ops'],
  elon: ['sys', 'ops', 'collab'],
  // Default: any agent can see the cross-cutting all-agents skills.
  _all: ['session', 'collab'],
}

function loadSkills() {
  try {
    const path = join(process.cwd(), 'src', 'data', 'skills.json')
    const raw = readFileSync(path, 'utf-8')
    const data = JSON.parse(raw)
    return Array.isArray(data.skills) ? data.skills : []
  } catch {
    return []
  }
}

export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS')
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type')
  if (req.method === 'OPTIONS') return res.status(200).end()
  if (req.method !== 'GET') return res.status(405).json({ error: 'GET only' })

  const agentRaw = (req.query.agent || '').toString().trim().toLowerCase()
  const categoryRaw = (req.query.category || '').toString().trim().toLowerCase()

  const all = loadSkills()

  let filtered = all
  if (agentRaw) {
    const cats = new Set([
      ...(AGENT_CATEGORIES[agentRaw] || []),
      ...(AGENT_CATEGORIES._all || []),
    ])
    filtered = all.filter(s => cats.has(s.category))
  } else if (categoryRaw) {
    filtered = all.filter(s => s.category === categoryRaw)
  }

  // Build category summary for the client.
  const counts = new Map()
  for (const s of filtered) {
    const key = s.category
    if (!counts.has(key)) counts.set(key, { category: key, label: s.categoryLabel || key, count: 0 })
    counts.get(key).count += 1
  }

  res.status(200).json({
    count: filtered.length,
    recipes: filtered.map(s => ({
      name: s.name,
      alias: s.alias || null,
      description: s.description,
      category: s.category,
      categoryLabel: s.categoryLabel || s.category,
    })),
    categories: [...counts.values()].sort((a, b) => a.label.localeCompare(b.label)),
  })
}
