export const navigationItems = [
  { label: 'Our Work', target: 'work' },
  { label: 'Our Studio', target: 'studio' },
  { label: 'Work with us', target: 'contact', solid: true },
]

export const portfolioCards = [
  {
    id: 'ambition',
    eyebrow: 'Brand system · 2025',
    title: 'Ambition Mechanical',
    category: 'Positioning, identity, and a digital home for the next generation of trades.',
    image: '/home2026/evidence-01.jpg',
    href: '/work/ambition-mechanical',
    tone: 'light',
  },
  {
    id: 'space-rising',
    eyebrow: 'Campaign · 2025',
    title: 'Space Rising',
    category: 'A launch campaign for people building what comes next.',
    image: '/space-congress/img/hero-launch.jpg',
    href: '/work/space-rising',
    tone: 'dark',
  },
  {
    id: 'included-health',
    eyebrow: 'Story · 2024',
    title: 'Included Health',
    category: 'A human story, built to move at the speed of trust.',
    image: '/home2026/evidence-03.jpg',
    href: '/work/included-health',
    tone: 'dark',
  },
  {
    id: 'isa-energy',
    eyebrow: 'Identity · 2024',
    title: 'ISA Energy',
    category: 'Making an essential service feel impossible to ignore.',
    image: '/home2026/evidence-02.jpg',
    href: '/work/isa-energy',
    tone: 'light',
  },
  {
    id: 'virtu',
    eyebrow: 'Hospitality · 2024',
    title: 'Virtu Hospitality',
    category: 'A point of view for places people remember.',
    image: '/caliente/assets/proj-phx-museum.jpg',
    href: '/work/virtu-hospitality',
    tone: 'dark',
  },
  {
    id: 'wolfpack',
    eyebrow: 'Growth · 2026',
    title: 'Wolfpack Plumbing',
    category: 'The marketing department for a company that did not have one.',
    image: '/wolfpack-site/assets/work-1.jpg',
    href: '/work/construction',
    tone: 'light',
  },
]

export const loopCards = [
  { kind: 'story', step: 1, label: 'Who we are', title: 'You already do the real work', display: 'You already do [[the real work.]]', tint: '#c9b896', tags: ['Construction', 'Trades', 'Founders', 'Nonprofits'], body: 'A creative production and systems company for construction companies, founders, nonprofits, and brands that do real work.' },
  { kind: 'story', step: 2, label: 'The problem', title: 'Nobody outside your office ever sees it', display: 'But nobody outside of your office {{ever sees it.}}', tint: '#7c8b99', tags: ['The gap', 'Best-kept secret'], body: 'The best proof you have is happening on site every day, and it dies there. No footage, no story, no reason for anyone new to believe you.' },
  { kind: 'story', step: 3, label: 'What we do', title: 'That is where we come in', display: 'That is where [[we come in.]]', tint: '#dd5420', tags: ['Social', 'Video', 'Websites', 'AI systems'], body: 'A day or two on site with your crew. Then we build everything around it: the content, the website, and the systems that keep it moving.' },
  { kind: 'story', step: 4, label: 'How it works', title: 'Your story, told and seen', display: 'AOM makes sure your story is [[told and seen.]]', tint: '#5e86a8', tags: ['We come to you', 'Nine cuts, one shoot', 'It keeps running'], body: 'The hero film, the bid-room version, the recruiting cut, and a month of short native posts, all out of the same two days.' },
  { kind: 'ask', step: 5, label: 'How we help', title: 'How can we help you?', display: 'How can we [[help you?]]', tint: '#d6de3c', options: ['We need web creativity', 'We need to get social', 'We need a video', 'We need a marketing team'], body: 'Pick the closest one. We reply with a plan, a price, and a date, not a discovery call.' },
  { kind: 'work', label: 'Work', title: 'Sunland Builders — brand film', meta: 'Brand film · 2026', metric: 'The bid-winning cut', image: '/wolfpack-site/assets/work-1.jpg', body: 'Two days on site, no script, no borrowed footage. The film now opens every bid presentation.' },
  { kind: 'quote', label: 'Client', title: 'Almost a million views', quote: 'The video you guys made us hit almost a million views organically (not kidding)', who: 'Founder · construction', body: 'One founder series, posted natively, no paid support. Organic first is the proof that the story works.' },
  { kind: 'service', label: 'Service', title: 'Video', service: 'Video', headline: 'Films that get watched', points: ['Brand films', 'Founder series', 'Job-site stories'], body: 'Production to final cut, in-house. Nine versions, three lengths, every platform native.' },
  { kind: 'work', label: 'Work', title: 'Founder series, Vol. 1', meta: 'Social system · 2026', metric: 'Almost a million views', image: '/home2026/evidence-03.jpg', body: 'A weekly founder series built to compound: one shoot day, a month of native cuts, a feed that works while you run the company.' },
  { kind: 'team', label: 'Studio', title: 'Small on purpose', image: '/home2026/evidence-01.jpg', body: 'The people who pitch the work make the work. No account layer, no handoff, no drift between the idea and what ships.' },
  { kind: 'work', label: 'Work', title: 'Desert Hope gala film', meta: 'Nonprofit film · 2025', metric: 'Giving up by two thirds', image: '/caliente/assets/proj-phx-museum.jpg', body: 'A three-minute film cut for a room of 400 donors, then re-cut for the eleven months between galas.' },
  { kind: 'service', label: 'Service', title: 'Web', service: 'Web', headline: 'Sites that convert', points: ['Marketing sites', 'Web apps', 'Design engineering'], body: 'Precise, editorial builds. Fast, monochrome, every pixel earning its place.' },
  { kind: 'quote', label: 'Client', title: 'A new league', quote: 'Your taking us into a new league', who: 'Owner · specialty trades', body: 'The work is judged by what it changes: the bids you get invited to and the crews who apply.' },
  { kind: 'work', label: 'Work', title: 'Crew stories — recruiting', meta: 'Campaign · 2025', metric: 'Three times the applicants', image: '/wolfpack-site/assets/work-3.jpg', body: 'Recruiting content shot with the crew who actually do the work. Three times the qualified applicants in one quarter.' },
  { kind: 'service', label: 'Service', title: 'Systems', service: 'Systems', headline: 'Social and AI workflows', points: ['Social systems', 'AI workflows', 'Always-on content'], body: 'Content engines with AI-powered workflows behind them, so the feed keeps moving without another meeting.' },
  { kind: 'post', label: 'Journal', title: 'Nobody watches your intro', meta: 'Journal · March 2026', headline: 'Nobody watches your intro', body: 'The first three seconds decide everything. Start in the middle, say one thing, and cut for the platform.' },
  { kind: 'cta', label: 'Start', title: 'Work with us', headline: 'Tell us what you need', body: 'Three questions. We reply with a plan, a price, and a date, not a discovery call.' },
]
